### ISSUE TITLE
Install: Requires bun installation

### ISSUE THREAD

**Issue by jeffgca** [hellhub-collective/cli#6]
If I run 

`hellhub --help`

I get 

```
➜ ~ hellhub --help
env: bun: No such file or directory
```

This is resolved by installing bun, so maybe the fix is just to explain in the readme that bun is required ( for now )

**Comment by fabio-nettis** [comment]
@jeffgca I surely do wonder why bun should be required, maybe the fact that we use `Bun.argv` but that should run on node just fine.

**Comment by fabio-nettis** [comment]
@jeffgca What package manager and command have you used to install the cli?

**Comment by jeffgca** [comment]
I just used npm, and previously had no bun installation. Installing bun fixed everything, so I think this is just an installation instructions gap?
