### ISSUE TITLE
Critical: Unable to resolve ascii art textfile paths

### ISSUE THREAD

**Issue by jeffgca** [hellhub-collective/cli#7]
If I run the example command from the readme:

`hellhub statistics --limit 10 --filters="planet:name:@contains:a"`

I get this error:

```
➜ ~ hellhub statistics --limit 10 --filters="planet:name:@contains:a"
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/Users/jeff/ascii/statistics.txt"

➜ ~
```

Is there some sort of initialization step I need to do?

**Comment by jeffgca** [comment]
Looks like this code is too optimistic about what directory it is currently in:

https://github.com/hellhub-collective/cli/blob/0f1da1d1fa3ada2ae9b54e1c0a911569c0464b05/utils/ascii.ts#L12-L14

It should be possible to always resolve this to wherever the cli is installed to, as opposed to the user's current directory.

**Comment by fabio-nettis** [comment]
@jeffgca would you be able to create a PR for this? Currently on the road and will not be able to fix this in a respectable timeframe.

**Comment by jeffgca** [comment]
Yeah I'll take a look this afternoon

**Comment by fabio-nettis** [comment]
Issue still not fixed after merge

**Comment by dealloc** [comment]
One option would be to get the path of the main file being executed, and build a relative path from there

A quick google:
- https://nodejs.org/api/modules.html#requiremain
- https://stackoverflow.com/questions/10265798/determine-project-root-from-a-running-node-js-application

**Comment by sebsebmc** [comment]
Or use a temporary directory as provided by the OS, using something like `os.tmpdir` or [`fs.mkdtmp`](https://nodejs.org/api/fs.html#fs_fs_mkdtemp_prefix_options_callback)

**Comment by jeffgca** [comment]
> Issue still not fixed after merge

Yeah it's a little hard to test how things will work once installed via npm. I'll look into this a bit more.

**Comment by jeffgca** [comment]
@fabio-nettis  I just updated from npm and it works perfectly!

**Comment by fabio-nettis** [comment]
@jeffgca Nice! Enjoy using it🤘🏻
